# Site wide configuration

title: Jack Chu
locale: en_US
description: I like to make things
logo: site-logo.png
search: true
url: https://jackchu.com

# Jekyll configuration

permalink:   /:categories/:year/:month/:day/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Site owner
owner:
  name: Jack Chu
  avatar: https://avatars.io/twitter/jack_chu/large
  email: jack@jackchu.com
  disqus-shortname: jackchublog
  twitter: jack_chu
  facebook: #username
  github: kamui
  stackexchange: stackoverflow.com/users/68255/jack-chu
  linkedin: chujack
  instagram: jackseviltwin
  flickr: #username
  tumblr: kamui
  pinterest: kamui
  weibo: #userid
  google:
    plus: #username
    analytics: UA-18119942-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
